//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfor
    {
        public int Sno { get; set; }
        public string Spassword { get; set; }
        public string Sname { get; set; }
        public string Ssex { get; set; }
        public string Sage { get; set; }
        public string Sdepartment { get; set; }
        public string Smajor { get; set; }
        public string Sclass { get; set; }
        public string Sgpa { get; set; }
        public string Scampus { get; set; }
    }
}
